# Generated by Django 3.1.3 on 2022-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='combData',
            fields=[
                ('subAccountNo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nicheng', models.CharField(max_length=100)),
                ('passportID', models.CharField(max_length=100)),
                ('AccountExistTime', models.CharField(max_length=100)),
                ('AssetVol', models.CharField(max_length=100)),
                ('user_fans_count', models.CharField(max_length=100)),
                ('GraphSpotList', models.JSONField()),
            ],
        ),
    ]
