# Generated by Django 3.1.3 on 2022-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comb_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combdata',
            name='GraphSpotList',
            field=models.JSONField(null=True),
        ),
    ]
